Resolve warning
alloc.c:48:20: warning: implicit declaration of function 'sbrk' is invalid in C99 [-Wimplicit-function-declaration]
    if ((current = sbrk(asize)) == END) {
                   ^
alloc.c:48:18: warning: incompatible integer to pointer conversion assigning to 'FreelistBlock *' (aka 'struct FreelistBlock *') from 'int' [-Wint-conversion]
    if ((current = sbrk(asize)) == END) {
                 ^ ~~~~~~~~~~~
2 warnings generated.

`sbrk` was removed in POSIX.1-2001, and GNU libc's unistd.h header file doesn't
expose it unless you use a magical `#define` to ask for it. So the compiler
assumed its return type is `int`. Use the magical `#define` to get the real
declaration.

Additionally, turn off `-Wreserved-macro-identifier`.